export const MESSAGE_TYPES = {
    PING: "PING",
    PONG: "PONG",
    WELCOME: "WELCOME",

    CREATE_ROOM: "CREATE_ROOM",
    JOIN_ROOM: "JOIN_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
    ROOM_STATE: "ROOM_STATE",

    PLAYER_JOINED: "PLAYER_JOINED",
    PLAYER_LEFT: "PLAYER_LEFT",

    GAME_START: "GAME_START",
    GAME_STATE: "GAME_STATE",

    INPUT: "INPUT"
} as const;